### ISSUE TITLE
New option for at shorting

### ISSUE THREAD

**Issue by carabao72** [manatools/dnfdragora#115]
**English**

Hello,

It would be interesting to take out the sort option "show only x86_64 ..." from the "all, update ..." menu to put it in a separate menu with another option "x86_64 and i686" and "i686 ". This would make it possible to use the other sorting options (all, update, installed, not installed).

The default choice of the program, i686 or x86_64, depends on the kernel installed.

In addition, the program should offer by default the latest version of a program and not the different versions.

Thank You

**French**
Il serait intéressant de sortir l'option de tri "afficher uniquement x86_64 ..." du menu "tous, mettre à jour..." pour le mettre dans un menu à part avec une autre option "x86_64 et i686" et "i686". Ce qui permettrait d’utiliser les autres options de tri (tous, mettre à jour, installés, pas installés). 

Le choix par défaut du programme, soit i686 ou x86_64 se fait en fonction du kernel installé.

De plus, le programme devrait proposer par défaut la dernière version d'un programme et non les différentes versions.

Merci

**Comment by anaselli** [comment]
Concerning option "show only x86_64 and..." is shown only for x86_64 linux machine. The implementation we have right now applies that to the chosen group (for fedora default is All, nut not for mageia) so that implementation should be reviewed a lot to give a different kind of filter and i won't do that now. But if you find someone who wants and can implement that we are ready to review a PR.
Regarding having an option to show only the latest package on a search i'm working on it but that is already in issue #113, so please follow the discussion there.

**Comment by carabao72** [comment]
Thank You
