### ISSUE TITLE
Add 'these' into 'Exclude packages'

### ISSUE THREAD

**Issue by yurchor** [manatools/dnfdragora#135]
Kristoffer Grundström has proposed to change the string in dnfdragora/dialogs.py:522 from "Exclude packages" to "Exclude these packages".

https://www.transifex.com/MageiaLinux/mageia/translate/#sv/dnfdragora/139429976/

What do you think about this?

**Comment by anaselli** [comment]
I seem that is needed to translate the hash key that we find in repo info... i've just found that in mageia repo info returns error though so i cannot be sure of that
Anyway if that is the nearest meaning why not... @Conan-Kudo wdyt?
If ok @yurchor are you able to change that and relate localization files?

**Comment by yurchor** [comment]
> If ok @yurchor are you able to change that and relate localization files?
Sure.

**Comment by Conan-Kudo** [comment]
`Exclude packages` is typically used as a unstructured formal command, because we don't know what the collection being excluded is. Adding `these` makes it more informal and makes the assumption we know what the collection is. That will be inconsistent with the language used everywhere else, so I'd rather not unless we'd like to go through and change the language everywhere, but also, adding `these` will make it more difficult for "simpler" translations, since not all of them have an equivalent to that word.

**Comment by yurchor** [comment]
> `Exclude packages` is typically used as a unstructured formal command, because we don't know what the collection being excluded is. Adding `these` makes it more informal and makes the assumption we know what the collection is. That will be inconsistent with the language used everywhere else, so I'd rather not unless we'd like to go through and change the language everywhere, but also, adding `these` will make it more difficult for "simpler" translations, since not all of them have an equivalent to that word.

+1
