### ISSUE TITLE
What is this error & how to deal with it ?!

### ISSUE THREAD

**Issue by Nokia808** [manatools/dnfdragora#138]
Hi. Please look to the attached screenshot.

What is this bug & how to deal with it ?! I'm facing it frequently ......

![error](https://user-images.githubusercontent.com/25375330/59767196-4a8a4680-9291-11e9-9d1f-e1bc158a82b8.png)

**Comment by Conan-Kudo** [comment]
It means something grabbed `dnfdaemon` socket and didn't cleanly exit.

Run `dnfdragora --exit` and then try again.

**Comment by Nokia808** [comment]
Is there a way to fix this behaviour from your side ? Is it inevitable ? 
And more important question: is dnfdaemon still viable project or already dead & not mantianed further ? It did not receive fixes since very long time & have many bugs not fixed till now !

**Comment by Conan-Kudo** [comment]
dnfdaemon doesn't need changes very often. We mostly have to adapt to changes to dnf. There's a larger plan of things to do, but I need to make time for implementing 

The issue comes up when dnfdragora quits in an unclean state, so it's not supposed to be inevitable, but I haven't figured out how to fix it yet. I *know* what causes the issue, it's just hard to fix.

**Comment by Nokia808** [comment]
Okay, take your time, but please give attention to the issue that dnfdaemon NOT recognize 3rd party repositories .... I'm already opened a bug about this, & this issue is annoying ......

**Comment by anaselli** [comment]
we do, but consider we are not so many and we have more than one tool only and also a real life :)
