### ISSUE TITLE
[Feature request] Add support to flatpak

### ISSUE THREAD

**Issue by Nokia808** [manatools/dnfdragora#151]
I'm not if this will addressed at all. Currently, dnfdragora has bugs staying very long time without fix, so is it possible to request new feature ...

I would like to request this because ultimate failure of GNOME software due to it's very unstable & buggy nature that far beyond what is already existing in dnfdragora ....  I tried "Apper" but it did not show any packages (whether .rpm or flatpak) so that I did not know if it support flatpak or not ....

I read about "KDE Discover" (plasma-discover) but there are reports about being disappointing like GNOME software & all these failures (GNOME software, Apper, KDE Discover) are due to PackageKit....... So, let we see if dnfdragora can manage better by being  able to manage flatpak directly without PackageKit or not ? If it can, then you can make it available by creating a flatpak specific dnfdragora plugin that by installing it user can add flatpak support ....

**Comment by yurchor** [comment]
offtopic: There were times when men were men and fix their bugs by themselves. Linux is not for modern people.

**Comment by anaselli** [comment]
even if dnfdragora has been thought with a front-end to back-end point of view, as it was for its ancient yumex-dnf they are (and the were too) mixed and a bit nested so a flatpak backend could probably be managed in some manner, but as you said we (and I) have a lot of bugs that were not forgot but simply not fixed by me or by receiving pull requests. I also have bugs that need some feed backs from users that unfortunately wait for fedora updates... so i cannot follow this request by now, but feel free to provide some code to work on I'll be happy to review it. Thanks, as always, for your report.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@anaselli, are you certain that this should remain closed? Unfortunately Flatpak becomes more popular during each day. Additionally, if this remains closed for that rationale, I dare not suggest that AppImage or Snap be supported. I despite Discover, yet I am unable to replace it with this until this lack of compatibility is remediated.

**Comment by anaselli** [comment]
Find a developer who wants to work on it and I'll open or push her work soon after.
I know I cannot work on it, sorry.
