### ISSUE TITLE
[UI - Look and feel] Some controls are puzzling. libYui limitation? Average user ideas.

### ISSUE THREAD

**Issue by aureoud-fr85** [manatools/dnfdragora#154]
Hi,
Sorry in advance for the pad I'm going to write.
I would like to contribute for dnfdragora's UI from a "average user" point of view. Let's see it.
**Main UI**
![dnfdragora_ugly_or_prototype](https://user-images.githubusercontent.com/66995112/88396764-46e5bf00-cdc3-11ea-9aac-cae6d28ef993.png)
At time of writing, dnfdragora (2.0.4) is stable, well functioning and seems do his job well done in order to install/remove packages. I think his UI has some counter intuitive visuals:
1) you could not find in any other GUI such menus for "File", "Information", "Options", "Help" as drop-down menus. I never see it elsewhere.
A menu is a menu. I think it's confusing despite presence of arrow icon next to the word File.
I think this prevents dnfdragora from being well integrated to his environment.

2) Also, dnfdragora logo and "Package Manager" should be centred.
In ncurses, we have a "Package manager" above "groups combox" but we also have a title for dnfdragora, duplicate strings?
3) What is this "0%" above Quit button. I know it is for progress bar but when dnfdragora is idle waiting for user's actions, user should not see it anymore. It is clutter.

Let's see Yast2 software manager:
![Yast_software_manager_leap15 2](https://user-images.githubusercontent.com/66995112/88402441-6680e580-cdcb-11ea-9b7f-c26d81e0020e.png)
No BIG buttons, no drop-down menu. You can see classics menus, in ncurses they are accessible.

**Dnfdragora Options.**
![dnfdragora_options_ui_ugly](https://user-images.githubusercontent.com/66995112/88402198-130e9780-cdcb-11ea-8c68-16f8e28459e4.png)
What a mess. Sorry, my personal thoughts.
4) Window title refers to User's preferences. No, it should be named "dnfdragora Options". Translation limitation?
5) What is "Proceed without confirmation" between two settings for querying update or refreshing repos? Translation?
6) Settings seems to be centred but there are mixing controls everywhere.
Titles for group options should be more separated, as if there is some line missing. Or, these options should be divided into tabs?
7) To activate logging, it shouldn't be in title but with a check box under.
8) There should be spaces around the options instead of feeling like the text is justified. My eyes could not determine where start options, where they finished.
Let's see KDE Systemsettings Polices KCM:
![KCM_Polices_Plasma5 19](https://user-images.githubusercontent.com/66995112/88403758-39353700-cdcd-11ea-9144-4ccc14f57a1c.png)
Controls are centred. Options divided clearly. Space around, no "justified texts".
Is it libYui limitations? Beta version?

Sorry for such negatives thoughts, but It's personal feelings. dnfdragora seems good for his job and it is good for free software community to have a common project with Mageia and Fedora for packages management.
But If my feeling for an UI his bad, I will not use it. It is right for every softwares I use, on my PC, on my mobile phone. A poor UI make me look elsewhere.
I know surely that I should have opened one issue for one every point I mentioned but it is a holistic feel.
Look and feel is important in my opinion. Also, dnfdragora will be default in near future for Mageia, a close-to-my-heart distribution and a beginning easy distribution, that I am on since Mandrake era.
Good job!

**Comment by anaselli** [comment]
I accept both negative and positive thoughts :) that means people use dnfdragora.

Unfortunatly most of you feel as "problems" are coming from libyui, and the main reason is that widgets should work and look the same either if you're using Qt, Gtk or ncurses. So of course that does not give so many possibilities, but i must admit i often cared about functionalities and since widgets are made in that way i din't work too much to layout (thing in which i'm not so good at :D)

Anyway I'll try to summarize a bit so i maybe forget things but not that i want to do it.
First **Menus** (bold yes) libyui implements them as menubutton I don't know what Suse does in YaST but certainly is not only libyui there. I recently implemented a **menubar** widget that is more similar to what we call nowadays a menu, see [libyui-bindings PR](https://github.com/libyui/libyui-bindings/pull/35) for instance, and next dnfdragora UI (Qt one here) should look like

![immagine](https://user-images.githubusercontent.com/1303486/88415758-4fe48980-cddf-11ea-9726-525ac40c159c.png)

I also removed the line with logo and  text inherited by rpmdrake look, to gain room as you can see.

**progress bar** you're right should be hidden, but there i had problems to show it on call because i can't understand well when i can hide it after e.g. when some events are really finished to be managed. But yes that is in my [TODO](https://github.com/manatools/dnfdragora/blob/master/TODO.md) list since i work on 2.0.x version. 

**User settings** you're right is a mess, something because of my laziness i gave up fighting with libyui layouts and as said i'm not good at that too. Concerning debug options well yes i used [YChekBoxFrame](https://github.com/libyui/libyui/blob/master/src/YCheckBoxFrame.h) to disable all at once, a checkbox means adding code to manage disabling other widgets.
_System settings_ i just add all in there.
And i think _KDE Systemsettings Polices KCM_ layout is a good example to implement user settings (or dnfdragora options maybe) giving a better layout, not that simple but can be done with libyui widget... i will think about it...

Thanks a lot for giving a feed back but also ideas, i appreciate it.

**Comment by aureoud-fr85** [comment]
I'm glaad it produces his effects. I would not want be disturbing writing this pad, but therefore some fresh look could be positive to the project.
Thank you so much for sneak peaking future UI which I think it goes into right direction.

I know so much how gnu/free softwares are written. You do not have the same ressources as counter part closed source softwares like at Apple, for example.

I suspected it was libYui involved all little point I suggested. I know I don't have knowledge to write application but I know how average user would use software as I love hunting bugs and do QA in my job.
Regards,

**Comment by anaselli** [comment]
I haven't managed data changing and saving, and i probably remove the _apply_ button, while the _cancel_ one could become _close_ one, but new setting (dnfdragora options) now looks like:
![immagine](https://user-images.githubusercontent.com/1303486/88483148-3d488c80-cf66-11ea-96f6-f2a93dc0c8ac.png)

We could also add icons on items, but it seem libyui-gtk does not manage that atm... new further fixing needed there...
What do you think? Are we going in the right direction?

**Comment by aureoud-fr85** [comment]
Yeah!
Things will go to the right direction!
Icons are a "plus" but non essential.
What does the string Perform transactions without ask for confirmation" mean in System options?
Perform install/update silently ?
If possible UI for entering time should have same width.
In logging options, control to change directory should be at last in order to have a "visually appealing order".

Good job well done. I will manage to check French translations when it will be possible.

**Comment by anaselli** [comment]
> What does the string Perform transactions without ask for confirmation" mean in System options?
In Yumex-dnf was a check box  called always yes iirc.
> Perform install/update silently ?
And also remove packages, i don't know how differently say that :D but any suggestions are welcome ;)

> If possible UI for entering time should have same width.
I gave up that, moreover running gtk is worst.
![immagine](https://user-images.githubusercontent.com/1303486/88483819-ac27e480-cf6a-11ea-907e-870317599a4b.png)
Maybe playing more with layout boxes... but it seems to depend on the before label string length...
> In logging options, control to change directory should be at last in order to have a "visually appealing order".
Sorry i can't get this last. could you explain it better?

**Comment by aureoud-fr85** [comment]
In that panel, you have 2 options with checkbox separated by a button to change directory.
In fact, I think same type of toggle should be placed next to them.
So button for change directory could be at final.
This will be "more beautiful". Personal feelings.

**Comment by aureoud-fr85** [comment]
What does the string Perform transactions without ask for confirmation" mean in System options?

In Yumex-dnf was a check box called always yes iirc.

    Perform install/update silently ?

And also remove packages, i don't know how differently say that :D but any suggestions are welcome ;)

I propose: "Run transactions on packages automatically without confirmations need"
But we should display a warning that packages should be removed automatically to satisfy dependencies.

**Comment by anaselli** [comment]
I think next is what we expected:
![immagine](https://user-images.githubusercontent.com/1303486/88485900-29a72100-cf7a-11ea-9535-d3d51c938c02.png)

And did you mean something like the picture below?
![immagine](https://user-images.githubusercontent.com/1303486/88485950-8276b980-cf7a-11ea-831e-ef38034c2f73.png)

and since I'm changing strings, what about **verbose** instead of "Debug level"?

**Comment by aureoud-fr85** [comment]
Very good!
"Debug level" is good as it refers to logging capabilities.
To be clearer, it could be "Add debug level outputs to log file".

**Comment by anaselli** [comment]
@aureoud-fr85 could you please test this commits from git following [Readme](https://github.com/manatools/dnfdragora/blob/master/README.md#from-sources-for-developers-and-testers-only) for developers and testers?

**Comment by aureoud-fr85** [comment]
Hi Angelo,
Coming back from sunny weekend, I must say I even do not know compile from sources, as I am not a developer.
