### ISSUE TITLE
update notification does not disapear by itself in Xfce

### ISSUE THREAD

**Issue by hannes101** [manatools/dnfdragora#178]
I can't exactly say, when this issue started to happen, it was not that long ago. Previously the notification of dnfdragora-update that X updates are available just vanished after the defined time of the Xfce notification plugin.
But now it does not disappear anymore and it always require a click on the notification to go away.
This is on a fully upgraded fedora 33 with Xfce 4.14 and dnfdragora-2.1.0-2.
All other notifications work as expected, but of course this could also be a bug in Xfce.

**Comment by anaselli** [comment]
Sorry it isn't clear to me which the problem really is for you. Our code does not close notification.
2.1.x added pystray notification instead of pynotify since the were conflicting using both in our experience.
According to [last documentation](https://github.com/moses-palmer/pystray/blob/v0.17.2/lib/pystray/_base.py#L218-L230) to remove notification we should need to do it by direct calling _remove_notification()_ but we didn't use any timer before an either now. 
If that is what you meant this is a workforme.

**Comment by hannes101** [comment]
Of course it's not dnfdragora, which closes the notification, but I suspect that the switch from pynotify to pystray might be the cause for the changed behaviour. Perhaps this new implementation is not properly implemented in Xfce.
I will investigate with the Xfce devs, if this is more on their side.
Thanks for the quick reply.

**Comment by hannes101** [comment]
I've opened an upstream bug at Xfce, https://gitlab.xfce.org/apps/xfce4-notifyd/-/issues/41

**Comment by alexmalykh** [comment]
I upgraded from F32 to F33 recently and confirm the issue. Session dbus monitoring has shown that notification requests coming from `dnfdragora-updater` have zero expiration timeout. According to freedesktop.org [notifications spec](https://specifications.freedesktop.org/notification-spec/latest/ar01s09.html):
> If -1, the notification's expiration time is dependent on the notification server's settings, and may vary for the type of notification. If 0, never expire.

That's why notification balloons don't dissappear automatically. The reason is [hard-coded zero](https://github.com/moses-palmer/pystray/blob/ccc699d32298ac7198664bd9a7afde7bbbccb577/lib/pystray/_util/notify_dbus.py#L84) in pystray dbus backend. Thus, the only way to hide the balloon is to call pystray's `hide()` method explicitly.

**Comment by hannes101** [comment]
But where is the bug then, pystray, xfce4-notifyd or in dnfdragora? Just to make sure it can be fixed in the right places.

**Comment by alexmalykh** [comment]
I think, it should be fixed in dnfdragora - close the notification balloon explicitly, as meant by `pystray` authors.

**Comment by anaselli** [comment]
well when we used pynotify we didn't close notification at all. KDE has a list of notification that must be close by user as far as i know, but notify compare only for a while.. is there a freedesktop specification for notification behavior, so that closing an issue for xfce does not mean opening a new one on another desktop? (adding @Conan-Kudo to see what he thinks about this too)

**Comment by alexmalykh** [comment]
Right, the balloons closed automatically because `notify2` sets _expire_timeout_ = -1 by default (see [here](https://bitbucket.org/takluyver/pynotify2/src/master/notify2.py#lines-205)). As [spec](https://specifications.freedesktop.org/notification-spec/latest/ar01s09.html) says, in this case it's up to notification daemon how to treat the balloon. `xfce4-notifyd` daemon closes such notifications in one second, but one of KDE/Plasma might have another defaults.

**Comment by anaselli** [comment]
So pystray cannot have the same behavior since they hardcoded 0, right?

**Comment by alexmalykh** [comment]
Yes. Balloons for `pystray` notifications are non-expiring and could be closed either by mouse click or programmatically.

**Comment by anaselli** [comment]
well, that means we'll see how we could manage it then... if someone had patches to provide... he's welcome too :D

**Comment by ochosi** [comment]
It isn't necessary to explicitly close the nofitication in order for the bubble to disappear in xfce4-notifyd.

If a notification is marked as "urgency:critical" xfce4-notifyd doesn't close it automatically which is what the spec says (see here: https://developer.gnome.org/notification-spec/)

So my presumption (without having read the code) is you set this urgency hint and a lower level would make the notification expire automatically.

**Comment by alexmalykh** [comment]
@ochosi there is no way to set urgency hint for a notification using `pystray`, because _hints_ parameter is [hardcoded](https://github.com/moses-palmer/pystray/blob/ccc699d32298ac7198664bd9a7afde7bbbccb577/lib/pystray/_util/notify_dbus.py#L83) as well (empty list).

**Comment by anaselli** [comment]
I opened an issue here
 https://github.com/moses-palmer/pystray/issues/84

**Comment by anaselli** [comment]
upstream seems to have accepted the suggestion to use -1!
Please let us know if it works now

**Comment by orschiro** [comment]
Great! Will this fix be shipped on Xfce 4.16?

**Comment by anaselli** [comment]
well it should be pystray only...

**Comment by oratosquilla-oratoria** [comment]
Can confirm that with the newest version of pystray (0.17.3) the balloon disappears automatically.

**Comment by anaselli** [comment]
great, so we should revert the code then before closing this issue :)

**Comment by Woi** [comment]
Packaging request for Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1903824#c4

**Comment by hannes101** [comment]
I made a scratch build for fedora 33.
https://koji.fedoraproject.org/koji/taskinfo?taskID=65149500

**Comment by Woi** [comment]
Updates for Fedora 34 and 35 (currently in development) are available. Fedora 32 and 33 might not get fixes.
See details in above bug description.

**Comment by anaselli** [comment]
does fedora 35 contain pystray 0.17.3?
