### ISSUE TITLE
dnfdragora opening as a line.

### ISSUE THREAD

**Issue by mdrakibur179** [manatools/dnfdragora#215]
![image](https://github.com/manatools/dnfdragora/assets/115276185/71672260-db12-4214-917c-2b9f61ef3a4c)

dnfdragora opening as a single line. Then I need to resize it to use. How to fix this problem?

**Comment by anaselli** [comment]
Thanks for reporting this issue, please add information such as if you're using gtk, or Qt, which desktop and distro. And of course which dnfdragora version you're using.

**Comment by anaselli** [comment]
In the mean while you could launch it from console or force it into your .desktop file with:
dnfdragora --fullscreen
and if you're using gtk as i suspect, try forcing the qt one

**Comment by mdrakibur179** [comment]
At first I didn't use any theme. It was default. Since then the problem is happening. Now I am using gtk theme. The problem is still the same.

**Comment by mdrakibur179** [comment]
I am using Fedora 38 Workstation. 
CPU: Ryzen 5 5600G
Mobo: Gigabyte B550M ds3h

**Comment by mdrakibur179** [comment]
![image](https://github.com/manatools/dnfdragora/assets/115276185/3d59c9d2-de96-4f06-9901-d96d1295b251)

this is the problem. I have install Fedora 38 Workstation twice for this problem. But no solution I found.

**Comment by anaselli** [comment]
No need to install system again :)
I think this is a libyui-gtk issue, but since i am the only active maintainer, it isn't easy for me. I will check and see if i find where the bug is when i have time. 
Please try to add dnfdragora-qt and libyui-qt and se if running "dnfdragora --qt" works better. If it does (and should) the only workaround i see is to use dnfdragora-qt and remove dnfdragora-gtk to have qt as default by now.

**Comment by mdrakibur179** [comment]
How can I add dnfdragora-qt and remove dnfdragora-gtk? Please can you explain?

**Comment by mdrakibur179** [comment]
Thank, buddy. I have found it. I just uninstalled "libyui-gtk" from dnfdragora, restart my device. And now it's ok.
