### ISSUE TITLE
Don't lock in Update mode

### ISSUE THREAD

**Issue by jimkp** [manatools/dnfdragora#33]
When starting with the '--update-only' dnfdragora is locked in that mode. When updating is complete or if no updates are found it should be possible to search or carry out any other function.

**Comment by anaselli** [comment]
well it has been started as update-only so i didn't expect to have an option to be back on normal functions :) OTOH if you start in normal way you can go in update view, so I'm not sure this is a real issue... we'll think about it though. Thanks for the report.

**Comment by jimkp** [comment]
It is common and accepted good practice to update before installing new packages or similar tasks.

**Comment by anaselli** [comment]
yeah, what i meant is that --update-only has been thought as show only updates, something that in mageia is MageiUpdate e.g. a different application. That's why i haven't thought to a go back normal view after updating, MageiaUpdate just says there nothing more to update :) And if that way is run after a desktop notify is more understandable maybe..
But i see your point and i think it isn't that hard to implement. Even if i'd prefer to start dnfdragora in a preferred mode, such as implementing #34 and close this as workforme.
Let's say that in the mean while you could always run dnfdragora in normal mode and select the updates filter, so that you can go back to normal mode after filtering all.

**Comment by jimkp** [comment]
Agreed, if #34 was implemented it would remove the need for this.

**Comment by anaselli** [comment]
issue #34 should be fixed now, closing this bug as work form thank you for the report.
