### ISSUE TITLE
RFE. Add a startup preference

### ISSUE THREAD

**Issue by jimkp** [manatools/dnfdragora#34]
Please provide a startup preference to select the mode to start in. An option to check for updates of startup as per Yumex-dnf would be preferable. This would also provide a faster startup.

As an aside starting in Group mode adds additional overhead which slows the startup so that dnfdragora compares poorly to yumex-dnf. Group mode seems a poor choice for the default mode.

**Comment by anaselli** [comment]
I think that is why you are using Fedora, Mageia has not that problem. But yes we need to do two actions for that, i believe:
1. move group caching into dnf-daemon
2. x user view, so that next start-up user feeling is always the same until he/she changes
  any helps is welcome especially for the first item.

**Comment by jimkp** [comment]
Thanks for the progress. Sorry don't know how to 'run from git'. No experience with that.

**Comment by anaselli** [comment]
into README.md you can find how to run from sources, or ask for an update to your distro.
This issue should be solved with my commit.
