### ISSUE TITLE
[Stability/security] Do not use the dnfdaemon running as root as long as possible

### ISSUE THREAD

**Issue by genodeftest** [manatools/dnfdragora#50]
By default, dnfdragora invokes dnfdaemon, which is running as root. This even happens for simple package requests. Any programming error might cause the dnfdaemon to break the system. To make those errors less dangerous, I suggest that dnfdragora only runs dnfdaemon as root if it needs to do transactions (i.e. install/uninstall software) or accesses the history database (if this feature comes back from yumex-dnf).

Installed software:
gtk3-3.22.12-2.fc25.x86_64
dnfdragora-1.0.1-5.git20170505.2a3b056.fc25.noarch
libyui-gtk-2.44.9-2.fc25.x86_64

**Comment by Conan-Kudo** [comment]
@genodeftest dnfdaemon has to be privileged to be able to lock and access the dnf yumdb. There's not a lot we can do about that. :(

**Comment by genodeftest** [comment]
No, the dnf database does not need to be locked to pull metadata. Just run dnf as ordinary user and you'll see that it can work, even several instances running at the same time in parallel.

**Comment by Conan-Kudo** [comment]
dnfdragora is also not really invoking dnfdaemon either. dnfdaemon runs as a system service. It's analogous to PackageKit, and has a similarly restrictive API. And even accessing privileged actions requires authentication via polkit.

**Comment by kkofler** [comment]
And the problem of pulling metadata as a regular user is that it will not use the shared system metadata, but download it to a user-specific location, so every user ends up redownloading it, and in particular, root will have to redownload it too. IMHO, this is not a good idea.

**Comment by anaselli** [comment]
@kkofler i don't know if that is a problem or not, but i think it is a dnfdaemon matter anyway. 
dnfdragora just uses dnfdaemon using its API
I made some tests locking db only when needed but all becomes so slow and unusable.
I will also try  the non-exclusive locking offered by dnfdaemon, but that should mean to create a new backend (with db locked this time) when needed e.g. transactions for instance, and again having a very slow transaction to get all cached (note that all of that is from yumex-dnf) could be bad again.

Said that, what happens if the systems updates some metadata and we have a not locked db? dnf could also work it just answers a question (single command) it does not have to show a coherent view of all information.

**Comment by genodeftest** [comment]
> And the problem of pulling metadata as a regular user is that it will not use the shared system metadata, but download it to a user-specific location, so every user ends up redownloading it, and in particular, root will have to redownload it too.

This is only true if not using `dnf-makecache`.

**Comment by Conan-Kudo** [comment]
This is not a dnfdragora issue. Closing.
