### ISSUE TITLE
Too much time for "Start looking for groups not in cache"

### ISSUE THREAD

**Issue by jamundso** [manatools/dnfdragora#52]
It's around 60 seconds **every time** dnfdragora is started. There must be a better way!

**Comment by anaselli** [comment]
Guessing you're yousing Fedora, are you displaying groups or all at start-up?

**Comment by jamundso** [comment]
Ah yes, the Groups display is the problem.

**Comment by anaselli** [comment]
Unfortunately that is a problem that comes from Fedora that does not have groups, and we need to cache info to retrieve packages from groups and viceversa. So since i can't see that nothing comes from dnf side we need to find someone who implements something in dnfdaemon for that. In the mean while you can can check the "_Do not show groups next start up_" following _Options->User preferences_ menu. Caching will be performed as soon as groups are chosen.

**Comment by genodeftest** [comment]
> Unfortunately that is a problem that comes from Fedora that does not have groups, and we need to cache info to retrieve packages from groups and viceversa.

Yes, Fedora does have groups. Yumex-dnf uses them and it takes literally no extra time to load the groups page in yumex-dnf. Dnfdaemon should already support this. https://dnf-daemon.readthedocs.io/en/latest/server.html?highlight=group looks like that too.

And if dnfdragora really needs to cache this info, how about loading it in background as soon as it starts, still allowing user interaction?
>  In the mean while you can can check the "Do not show groups next start up" following Options->User preferences menu. Caching will be performed as soon as groups are chosen.

Hm, that sounds like a pretty dirty hack…

**Comment by jamundso** [comment]
> And if dnfdragora really needs to cache this info, how about loading it in background as soon as it starts, still allowing user interaction?

I completely agree. I think there is a better possible outcome with this.
Can this be re-opened please? Perhaps tagged as an Enhancement...?

**Comment by anaselli** [comment]
Well, 

> Hm, that sounds like a pretty dirty hack…

it isn't it just allows Fedora user to work as yumex-dnf, despite of the problem we have now.

> And if dnfdragora really needs to cache this info, how about loading it in background as soon as it starts, still allowing user interaction?

We can't, we have no threads, and that's why it must be addressed to dnfdaemon.

> Yes, Fedora does have groups. 
Well they are not the same as other distros, but i left @Conan-Kudo to explain what i mean.

**Comment by Conan-Kudo** [comment]
What @anaselli means by Groups is that Fedora doesn't actively use the RPM Groups tag anymore. dnfdragora's default configuration is parse the Group tag to organize packages. However, the Group tag is utter nonsense in Fedora since people stopped properly maintaining the organizational structure there. Well, that and the Red Hat Linux 9 groups definition is really bad compared to what SUSE and Mageia do.

Anyway... Fedora uses composition groups (what most people call "comps groups"), which are specifically a type of object from Anaconda to represent installable collections, since the RPM collections feature never really worked. SUSE's equivalent is Patterns, which we don't support at all since DNF doesn't yet.

Because comps groups are a different type of metadata, it has to be handled differently. There are also some issues in the DNF API for handling comps groups, in part because the underlying libcomps library sucks. We do some extra stuff in dnfdragora to make this not as crappy, but figuring out a way to do this sanely in dnf(daemon) so that its not so bad is difficult.

The two fundamental issues are:

1. dnfdaemon can't get the "full names" (including translated names) directly from DNF
2. comps groups are an N:M relationship, so we need to reparse it multiple times to categorize things correctly

Solving (1) is tricky due to having to touch all the underlying API layers, and solving (2) is almost impossible without inducing lockups everywhere. One thing we could do is possibly have it load the group package list on-demand, but that just staggers out the load requests rather than buffering them up at the beginning. It might be an acceptable way to handle it for now, though.

**Comment by jamundso** [comment]
I should think the "comps" files already in /var/cache/dnf, or some existing interface to them, could be utilized.
I guess that's why 
[https://dnf-daemon.readthedocs.io/en/latest/server.html?highlight=group](url)
specifically notes that Group support is Under Development. :)

**Comment by anaselli** [comment]
as you can see [dnfdaemon](https://github.com/manatools/dnfdaemon) is now under manatools developement since @Conan-Kudo took its ownership, so I don't know what is still valid in that documentation, I mean `Under Development` means not developed by old maintainers...

**Comment by Conan-Kudo** [comment]
Well, it means the feature isn't fully there, which is definitely true.
