### ISSUE TITLE
Add Ctrl+Q option to Quit

### ISSUE THREAD

**Issue by AdmiralAsshat** [manatools/dnfdragora#53]
Alt+F -> Q works in a pinch, but Ctrl+Q or Ctrl+W as a hotkey for Quit is pretty universal in any app that has a Menu bar. It would be nice to see it implemented in dnfdragora.

**Comment by anaselli** [comment]
[Quit button](https://github.com/manatools/dnfdragora/blob/master/dnfdragora/ui.py#L461) has a shortcut. Libyui allows to choose it by adding a "&" before the letter we wanted and if it is not already taken is assigned to that widget. So "&Quit" means alt-q, and we try to have a similar behavior for all the manatools.
Consider also that we left to translators that shortcut so that is also localized and looking hopefully equal for any manatools application too.

**Comment by anaselli** [comment]
Closing as work-forme
