### ISSUE TITLE
Add Column for Repository on Search Results

### ISSUE THREAD

**Issue by AdmiralAsshat** [manatools/dnfdragora#57]
Using DNF on the command line to list of install an app will also indicate which repository it's pulling the app from. This would be nice to see in dnfdragora, particularly when the package is available from multiple repositories.

A "Repo." column is also present in Yumex, which dnfdragora will replace, and so I suggest that we should add it in order for dnfdragora to reach feature parity with Yum Extender.

**Comment by anaselli** [comment]
I will check yumex-dnf code, because even if it isn't a problem to show that information, I'm not sure it is also relevant for installing purpose, I mean if we have a couple of repositories with the same package and version the first one is shown, but dnf could choose the latter for any different reason (mirror, errors etc) @Conan-Kudo maybe can give me some more info on it.

**Comment by Conan-Kudo** [comment]
If "sticky vendors" are ever implemented in DNF, this could become more important. But it's still useful information, I think.

**Comment by anaselli** [comment]
but is it better to add a line into package information or columns that make dnfdragora larger?

**Comment by Conan-Kudo** [comment]
Probably better in the package information description.
