### ISSUE TITLE
Display of GUI of dnfdragora is highly unlogical & need rebuilding ! Please your kind attention !

### ISSUE THREAD

**Issue by Nokia808** [manatools/dnfdragora#62]
Hi. Currently, dnfdragora on Fedora has unlogical GUI due to:

1) most importantly, size of individual columns are very wide make user unable to see enough amount of descriptions & data ! User need to scroll  horizontally for that !

You need to decrease width of individual columns. It will be very great if you take yumex-dnf as an ideal because it has very logical GUI.

2) currently, dnfdragora has no "package size" column ! In addition to "Arche", "Version", ....... there is need to add column for "Package size". 

Users need to know exactly how much size of package(s) that she/he need to download .....

Best & thank you for your very hard efforts !

**Comment by anaselli** [comment]
As far as **column size** you need to move discussion to [libyui project](https://github.com/libyui)
yumex-dnf has been developed using GTk, we use a gui abstraction instead (libyui), to have also Qt and ncurses, that of course have some limitation.

Regarding **package size** we could add a column or information on package info field. Size could be interesting to know, however not always relevant, since -for the most- it isn't a matter of one package but all of it dependency, e.g. the sum. I can't remember if that information, i.e. size, is shown in the summary/confirmation dialog during installation.

**Comment by Nokia808** [comment]
Thank you for your kind response.

1) regarding size of individual columns: I'm not programmer & I did not know these details.
However, I feel that it is better that you should move discussion to libyui, because you can understand them language as a programmer while all what can I give is a suggestions appear to me reliable while they could be impossible due to package(s) limitations beyond my understanding ....

2) regarding size of package it is very important when about downloading a game to see size of it's data size. Some of them my reach to 1.4 or even to 2 GB.

**Comment by anaselli** [comment]
I see your layout problems, when i ask for moving dicussion to libyui, i do because i would like our upstream abstraction library can know that more people have problems in layout and not only a developer.
Said that libyui is missing a gtk developer and that is a pity, I cannot fix also upstream bugs

**Comment by Nokia808** [comment]
O.K but just give me the exact link to post my complain for libyui. When I clicked over "libyui", I saw many titles ..... Which of them ? 1st "libyui"

**Comment by anaselli** [comment]
[libyui-GTk](https://github.com/libyui/libyui-gtk) if you use libyui gtk or [libyui-Qt](https://github.com/libyui/libyui-qt) in the case you're using QT istead

**Comment by Nokia808** [comment]
Hi. Both of them installed on my system (libyui-gtk & libyui-qt) ! I installed dnfdragora on Fedora 24 then upgrade - with dnfdragora - to Fedora 26.

Is this normal ? Is there a switch option between them ?

I'm not programmer & not know about these packages ...

**Comment by anaselli** [comment]
yes, they can stay both on the system without any problems.
If you are not sure of which you're using, open e terminal and run 
dnfdragora --gtk
then look at it and see if it is the layout you're using every day working.
Then close it and run
dnfdragora --qt
If you're using qt you should see the same layout.
if you ever need to run dnfdragora in ncurses to force it just run
dnfdragora --ncurses

**Comment by anaselli** [comment]
An option you could also use is --fullscreen

**Comment by Nokia808** [comment]
I test --qtk & --qt 
Both same with only one different: --qtk associated with dark theme that I activated in Cinnamon, while --qt not.
By default --qtk is daily option on my system.

Full screen not solve problem. 

I will open bugs in both qtk & qt.

**Comment by kn00tcn** [comment]
@anaselli is storing the window size (or at the very least maximized vs windowed) not part of the app's control?

the way the rows expand padding is bizarre, but i guess the qt version does it as well, so these rows are not dragora's fault?

**Comment by anaselli** [comment]
As far as i can say i can give a minimu size to dialog, but that does not work as expected GUI behaviour, just number of rows and columns to be consistent with the ncurses ui.
Frames as i used in dnfdragora works better in QT yes, even if sometimes i had some problems there too. In past i fixed some ibyui gtk issues, but now i can hardly follow manatools and dnfdragora...

**Comment by kn00tcn** [comment]
such a disappointing situation, both dragora & yumex have problems, not sure why someone from fedora didnt step up to continue yumex... funny thing is i switched to commandline months ago so i can uninstall packages i dont need (when they appear as update, yumex cant uninstall from that view), i pretty much use the frontends to view update info or search

**Comment by anaselli** [comment]
i see, fwiw i used libyui to have a code that can be run with ncurses, gtk and qt, obviously you can't have all, since same code is used for all of them, so all i can say is try to push upstream  [libyyui-gtk](https://github.com/libyui/libyui-gtk) for these issue

**Comment by kn00tcn** [comment]
IF it's libyui specific, if it's not something as simple as choosing the wrong component (as the rows appear to be based on percentage height instead of fixed height, it's not something any app should ever decide to do for button areas, but it's exactly the right component for the information pane)

**Comment by Nokia808** [comment]
Hi. I tried new option:

dnfdragora --gtk

it did not alter any thing !! No any improvement !! I did not detect any change!!

Moreover, it become more bad: now, when I change widths of various column then close dnfdragora, then re-launch it then dnfdragora DO NOT REMEMBER custom sizes & I have to resize them again !! 

I does not understand why you closed this bug ?!!

**Comment by anaselli** [comment]
Easy man, that because unfortunately is not a dnfdragora issue, but as said above [libyi-gtk](https://github.com/libyui/libyui-gtk). They (libyui upstream) are looking for help in there...

**Comment by Nokia808** [comment]
@anaselli 

Hi. Please to see the response of libyi-gtk . He closed the issue with following final statement:

"Simple solution: Don't do that in that program. Use the UI the way it was intended to be used."

What he was mean by this ? Is it to me or to dnfdragora developer ?

See the following:
https://github.com/libyui/libyui-qt/issues/70

**Comment by kn00tcn** [comment]
libyui dev didnt understand the specific issue you had, i made a reply there & will repeat here

the main issue is that column widths auto expand to the longest text, so a long package name will cause the name column to be pointlessly long

i dont know if libyui or dnfdragora has the power to maybe disable this so that there is a default column size with ... for long text

my issue that for some reason i never made a screenshot of is the following:

![kn-dnfdragora-libyui-verticalsize](https://user-images.githubusercontent.com/8087411/54859459-ca7d3080-4ce3-11e9-8163-182ed92ca2b3.png)

same question, does dnfdragora or libyui control this behavior?

**Comment by anaselli** [comment]
@kn00tcn but maybe your issue is related to libyui dev comment. I should make a test as soon as possible in which i add a title to widgets, if the empty room becomes less then that could be an explanation.
@Nokia808 another test i should make is to use their example for table and see it columns have same issue, but i seem to recall it was. That only to see if our implementation of YCBTable (that has not been accepted by libyui ncurses developer) is the reason... just to be sure.
- [ ] Test with title widget addition
- [ ] Test with YTable columns

In any case those are two different issues...

**Comment by anaselli** [comment]
>     * [x]  Test with YTable columns
[See comment here](https://github.com/libyui/libyui-qt/issues/70#issuecomment-475855535)

**Comment by kn00tcn** [comment]
yep, two different issues, reason i posted in this thread was due to OP's title of 'unlogical' somewhat implying multiple issues
