### ISSUE TITLE
Can you make searching bringed about by hit "Enter"  key ??

### ISSUE THREAD

**Issue by Nokia808** [manatools/dnfdragora#63]
Hi. Currently, after user type a search item(s), she/he need to click on "search" within dnfdragora GUI to activate searching process. It will be very useful & convenient to make it possible to activate searching process by hit (click) the key "enter" of keyboard. This already a feature in yumex-dnf ....

Best.

**Comment by anaselli** [comment]
hi, this is not a yumex-dnf fork, however Search button is the selected button on start up, in that case it should work, but in gtk for a libyui bug iirc. If you later select another push button that behavior does not work any more though, since the selection changed.
You can always get search button activated but using "**Alt-S**" in English or "Alt" and the underscored letter in your button translated name. Open a bug if for your localization you have shortcut conflicts, eventually.

**Comment by Nokia808** [comment]
Thank you very much, Alt+S combination work fine !

**Comment by Nokia808** [comment]
I have suggestion regard this: add a notification box, inside it "Alt+S", appearing when mouse pointer located over "search". By this way you will bring attention of user to this feature & not make heir/him beleave, like me, that no such feature available.

Best.

**Comment by anaselli** [comment]
i think we need more a user manual :)
